#! /bin/sh

function Read_Relay() {
/data/rgpio/modpoll/arm-linux-gnueabihf/modpoll -m rtu -b 115200 -p none -d 8 -1 -r 2 -s 1 -c 1 $1
}

function Read_Input() {
/data/rgpio/modpoll/arm-linux-gnueabihf/modpoll -m rtu -b 115200 -p none -d 8 -1 -r 11 -s 1 -c 1 $1
}

function Write_Relay() {                                                                                                
/data/rgpio/modpoll/arm-linux-gnueabihf/modpoll -m rtu -b 115200 -p none -d 8 -1 -r 3 -s 1 -c 1 $1 $2
} 

#
# Check if read or Write command
#
if [ "$#" -eq 2 ]; then
	msg=$(echo -n $($1 $2) | awk '{print $NF}')
	number=$(($msg))
	if ((number >= 0 && number <= 255)); then
        	echo -n $msg
        	exit 0
	else          
        	exit 1
	fi
else
	msg=$(echo -n $($2 $3 $1) | awk '{print $NF}')                                                                                         
	if [ "$msg" == "reference." ]; then
		exit 0
	else
		exit 1
	fi
fi

