#! /bin/sh
#
# Prevent running more than onece
#
OWN_LOCK=/bin/false 
#LOCK_FILE=/var/lock/subsys/mod_generator.run 
LOCK_FILE=/data/rgpio/mod_generator.run
 
clean_up() { 
  $OWN_LOCK && rm -f $LOCK_FILE 
} 
 
trap clean_up EXIT SIGINT SIGKILL 
     
if [ -e $LOCK_FILE ]; then 
    	echo "Lock file exists, exiting." >&2 
    	exit 1 
else 
    if ! touch $LOCK_FILE; then 
      echo "Failed to create lock file, exiting." >&2 
      exit 1 
    fi 
    OWN_LOCK=/bin/true 
fi 
 
function Set_AC_Source() {
dbus -y com.victronenergy.settings /Settings/SystemSetup/AcInput1 SetValue $1
}

function Get_AC_Source() {
dbus -y com.victronenergy.settings /Settings/SystemSetup/AcInput1 GetValue
} 

#
# Check if read or Write command
#

if [ "$#" -eq 1 ]; then
	msg=$(echo -n $($1))
	number=$(($msg))
	if ((number >= 0 && number <= 255)); then
        	echo -n $msg
        	exit 0
	else
        	exit 1
	fi
else
	msg=$(echo -n $($2 $1))
	if [ "$msg" == "0" ]; then
		exit 0
	else
		exit 1
	fi
fi
